### ISSUE TITLE
stop程序的时候，如果当前在线的人数比较多的话，会卡死。

### ISSUE THREAD

**Issue by szsailing** [spyderj-cn/wifidogx#3]
主要表现在等待删除iptables命令的waitpid上。是否有办法解决？

**Comment by spyderj-cn** [comment]
是命令一直未执行完还是执行完了但waitpid没有返回?

**Comment by szsailing** [comment]
应该是一直未执行完。

**Comment by spyderj-cn** [comment]
看起来像是个系统层面的问题，可能排查起来有点难度。要不你试试用ipset ？

**Comment by spyderj-cn** [comment]
我的qq号是2737502585， 要不你加我下 ？
